# Generated by Django 3.0.8 on 2020-07-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=47)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=47)),
                ('department', models.CharField(max_length=9)),
            ],
        ),
    ]
